---
title: "abstract_table"
output: html_document
date: "2023-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(kableExtra)
```


```{r}
source("C:/Users/klw00024/Documents/SPRING-/means_by_trimester.R")
```

```{r}
abstract_table <- rbind(combined_global, combined_quality, combined_latency, combined_duration, combined_efficiency, combined_disturbances, combined_daytime_dysfunction)
names(abstract_table) <- stringr::str_replace(names(abstract_table), "_", " ")
colnames(abstract_table)[colnames(abstract_table) == 'Estimate'] <- "Estimate (SE)"
colnames(abstract_table)[colnames(abstract_table) == 'Cohens d'] <- "Cohen's d"
abstract_table$Baseline[abstract_table$Baseline == "1.67 (0.6)"] <- "1.67 (0.60)"
abstract_table$Baseline[abstract_table$Baseline == "1.62 (0.5)"] <- "1.62 (0.50)"
abstract_table$Baseline[abstract_table$Baseline == "1 (0.97)"] <- "1.00 (0.97)"
abstract_table$`Second Trimester`[abstract_table$`Second Trimester` == "1 (0.82)"] <- "1.00 (0.82)"
abstract_table$`Third Trimester`[abstract_table$`Third Trimester` == "7 (3.6)"] <- "7.00 (3.6)" 
abstract_table$`Third Trimester`[abstract_table$`Third Trimester` == "1.25 (1)"] <- "1.25 (1.00)" 
abstract_table$p[abstract_table$p == "0.2"] <- "0.20" 
abstract_table$`Cohen's d`[abstract_table$`Cohen's d` == "0.3"] <- "0.30" 
abstract_table$`Cohen's d`[abstract_table$`Cohen's d` == "0.1"] <- "0.10" 
```

```{r}
abstract_table %>% 
  kbl(caption = "Table 1. Effects of SPRING Intervention on Sleep Outcomes Across Pregnancy") %>% 
  kable_classic() %>% 
  footnote("Global PSQI Score points range 0-21; All other points range 0-3; 0 indicates no sleep difficulties and higher scores indicate increasingly severe sleep difficulties; Efficiency is percentage of total time in bed / sleep duration; Bold results are significant.") %>% 
  column_spec(7, bold = ifelse(abstract_table$p == "0.01", TRUE, FALSE))
```

